export const FILTERS = ['active', 'inactive']
export const UPDATE_FILTER = 'UPDATE_FILTER'

export const GET_TODOS_SUCCESS = 'GET_TODOS_SUCCESS'
export const GET_TODOS_FAILURE = 'GET_TODOS_FAILURE'

export const POST_TODOS_SUCCESS = 'POST_TODOS_SUCCESS'
export const POST_TODOS_FAILURE = 'POST_TODOS_FAILURE'

export const UPDATE_TODO_SUCCESS = 'UPDATE_TODO_SUCCESS'
export const UPDATE_TODO_FAILURE = 'UPDATE_TODO_FAILURE'

export const DELETE_TODO_SUCCESS = 'DELETE_TODO_SUCCESS'
export const DELETE_TODO_FAILURE = 'DELETE_TODO_FAILURE'